version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: simutrade
      MYSQL_USER: simstock_dev
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./Backend
    environment:
      DATABASE_URL: mysql+pymysql://simstock_dev:1234@db/simutrade
      NEWS_API_KEY: "${NEWS_API_KEY}"
      SECRET_KEY: "${SECRET_KEY}"
    depends_on:
      - db
    ports:
      - "8000:8000"
